language: ruby
rvm:
  - 2.3.1

branches:
  only:
  - master

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - bundle exec rubocop
  - bundle exec rspec spec

deploy:
  provider: heroku
  app: equipeoz-beta
  api_key:
    secure: "8b39162c-dfaf-4d4a-9645-f8102d24fa77"
  strategy: git-ssh
  run: rails db:migrate

notifications:
  email:
    recipients:
      - alan@campuscode.com.br
      - vinylimaz@live.com
      - rcecosta@gmail.com
      - erisonjapa@gmail.com
      - flavio.visetti@gmail.com
      - erickcontato@hotmail.com
    on_success: always
    on_failure: always
